// Generates src/money/iso4217.generated.ts from the official ISO 4217 list
// ("list one", published by SIX on behalf of ISO).
//
// The script never touches the network: download the list explicitly, review
// it if you like, then pass the file in. Generation is a pure transformation
// of a known input.
//
//   curl -fsSL -o /tmp/list-one.xml \
//     https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml
//   pnpm --filter @spend-tracker/core generate:iso4217 /tmp/list-one.xml
//
// Funds and entries without minor units (precious metals, testing codes) are
// left out: they aren't currencies people hold in personal accounts.
import { readFile, writeFile } from "node:fs/promises";

const OUTPUT = new URL("../src/money/iso4217.generated.ts", import.meta.url);

const source = process.argv[2];
if (!source) {
  console.error(
    "Usage: generate-iso4217.mjs <path to ISO 4217 list-one.xml> (see the header comment)",
  );
  process.exit(1);
}
const xml = await readFile(source, "utf8");

const published = /<ISO_4217 Pblshd="(\d{4}-\d{2}-\d{2})"/.exec(xml)?.[1];
if (!published) throw new Error("Publication date not found in the source.");

/** @type {Map<string, number>} */
const minorUnits = new Map();
for (const [, entry] of xml.matchAll(/<CcyNtry>([\s\S]*?)<\/CcyNtry>/g)) {
  const code = /<Ccy>([A-Z]{3})<\/Ccy>/.exec(entry)?.[1];
  const units = /<CcyMnrUnts>(\d)<\/CcyMnrUnts>/.exec(entry)?.[1];
  const isFund = /<CcyNm IsFund="true">/.test(entry);
  if (!code || units === undefined || isFund) continue;
  const value = Number(units);
  const previous = minorUnits.get(code);
  if (previous !== undefined && previous !== value) {
    throw new Error(
      `Inconsistent minor units for ${code}: ${previous} vs ${value}`,
    );
  }
  minorUnits.set(code, value);
}
if (minorUnits.size < 100)
  throw new Error(
    `Only ${minorUnits.size} currencies found; is the source valid?`,
  );

const lines = [...minorUnits.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([code, units]) => `  ${code}: ${units},`);

await writeFile(
  OUTPUT,
  `// Generated by scripts/generate-iso4217.mjs. Do not edit by hand.
// Source: ISO 4217 list one, published ${published} (SIX, on behalf of ISO).
// Excludes funds and entries without minor units.

/** Publication date of the ISO 4217 list this table was generated from. */
export const ISO4217_PUBLISHED = "${published}";

/** Number of minor-unit digits per active ISO 4217 currency code. */
export const ISO4217_MINOR_UNITS = {
${lines.join("\n")}
} as const;
`,
);
console.log(
  `Wrote ${minorUnits.size} currencies (ISO 4217 list published ${published}).`,
);
